sonar.organization=demo-march-2026

sonar.projectKey=demo-march-2026_cohort

sonar.projectName=DevSecOps Python Demo

sonar.sources=src

sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/htmlcov/**

sonar.sourceEncoding=UTF-8
